### ISSUE TITLE
RHEL Dockerfile: Error from yum with .rpm install

### ISSUE THREAD

**Issue by pcunning-rh** [CrowdStrike/Dockerfiles#25]
With the RHEL UBI Dockerfile, the step of `yum` to install the falcon-sensor.rpm locally encountered an issue
```
Error: Transaction test error:
  package falcon-sensor-6.20.0-11711.el8.x86_64 does not verify: no digest
```

Moved to `rpm -ivh --nodigest --nofiledigest` allowed for successful install
```
Complete!
warning: /tmp/falcon-sensor.rpm: Header V4 RSA/SHA256 Signature, key ID b88c500b: NOKEY
Preparing...                          ########################################
Updating / installing...
falcon-sensor-6.20.0-11711.el8        ########################################
Created symlink /etc/systemd/system/multi-user.target.wants/falcon-sensor.service → /usr/lib/systemd/system/falcon-sensor.service.
```

**Comment by pcunning-rh** [comment]
Attempted build on a different machine and didn't run into the RPM error... may need to triage this issue further.

On RHEL 7.8 with docker 1.13.1, build fails with `yum` error regarding no digest.
On RHEL 8.4 with buildah 1.19.8, image build succeeds with no `yum` errors

**Comment by redhatrises** [comment]
Hello,

Are you trying to use the EL8 rpm on EL7 systems? If so, that might be your problem.

**Comment by pcunning-rh** [comment]
> Hello,
> 
> Are you trying to use the EL8 rpm on EL7 systems? If so, that might be your problem.

Yes, the build that was failing was using the EL8 RPM with the ubi8 base image on an EL7 build node.

**Comment by redhatrises** [comment]
Closing as this repo is now deprecated and registry.crowdstrike.com should be used instead.
